<?php
/**
 * DietPress Tools.
 *
 * Handles import/export, predefined profiles, and automatic recommendations.
 * All actions use AJAX endpoints with nonce + capability checks.
 *
 * @package DietPress
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Core_Diet_Tools {

	/**
	 * Register AJAX hooks.
	 */
	public function init() {
		add_action( 'wp_ajax_core_diet_export', array( $this, 'ajax_export' ) );
		add_action( 'wp_ajax_core_diet_import', array( $this, 'ajax_import' ) );
		add_action( 'wp_ajax_core_diet_apply_profile', array( $this, 'ajax_apply_profile' ) );
		add_action( 'wp_ajax_core_diet_analyze', array( $this, 'ajax_analyze' ) );
		add_action( 'wp_ajax_core_diet_save_recommendations', array( $this, 'ajax_save_recommendations' ) );
		add_action( 'wp_ajax_core_diet_restore_tab', array( $this, 'ajax_restore_tab' ) );
	}

	/* ============================
	 * Export
	 * ============================ */

	/**
	 * AJAX: Export settings as JSON.
	 */
	public function ajax_export() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		$settings = get_option( Core_Diet_Settings::OPTION_NAME, Core_Diet_Settings::get_defaults() );

		$export = array(
			'plugin'   => 'dietpress',
			'version'  => CORE_DIET_VERSION,
			'exported' => current_time( 'c' ),
			'settings' => $settings,
		);

		wp_send_json_success( $export );
	}

	/* ============================
	 * Import
	 * ============================ */

	/**
	 * AJAX: Import settings from JSON.
	 */
	public function ajax_import() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		if ( empty( $_FILES['file'] ) || ! isset( $_FILES['file']['name'] ) ) {
			wp_send_json_error( __( 'No file uploaded.', 'wpo-tweaks' ) );
		}

		// Validate file extension (.json not in WP default allowed types).
		$filename  = sanitize_file_name( wp_unslash( $_FILES['file']['name'] ) );
		$extension = strtolower( pathinfo( $filename, PATHINFO_EXTENSION ) );
		if ( 'json' !== $extension ) {
			wp_send_json_error( __( 'Invalid file type. Please upload a JSON file.', 'wpo-tweaks' ) );
		}

		// Read and parse file content. The tmp path is generated by PHP, and
		// is_uploaded_file() rejects anything that is not this request's upload.
		$tmp_path = isset( $_FILES['file']['tmp_name'] ) ? sanitize_text_field( wp_unslash( $_FILES['file']['tmp_name'] ) ) : '';
		if ( empty( $tmp_path ) || ! is_uploaded_file( $tmp_path ) ) {
			wp_send_json_error( __( 'Upload failed.', 'wpo-tweaks' ) );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- reading the PHP upload tmp file; WP_Filesystem transports (FTP, SSH) cannot access it.
		$content = file_get_contents( $tmp_path );
		if ( false === $content ) {
			wp_send_json_error( __( 'Could not read the uploaded file.', 'wpo-tweaks' ) );
		}

		$data = json_decode( $content, true );
		if ( json_last_error() !== JSON_ERROR_NONE || ! is_array( $data ) ) {
			wp_send_json_error( __( 'Invalid JSON format.', 'wpo-tweaks' ) );
		}

		// Validate it's a DietPress export. The legacy 'core-diet' id (used by
		// exports made before 3.1.0 and by the retired standalone plugin) is
		// still accepted for backward compatibility.
		$valid_ids = array( 'dietpress', 'core-diet' );
		if ( ! isset( $data['plugin'] ) || ! in_array( $data['plugin'], $valid_ids, true ) || ! isset( $data['settings'] ) ) {
			wp_send_json_error( __( 'This file is not a valid DietPress export.', 'wpo-tweaks' ) );
		}

		// Sanitize through the same callback used by Settings API.
		$sanitized = Core_Diet_Settings::sanitize( $data['settings'] );

		update_option( Core_Diet_Settings::OPTION_NAME, $sanitized );

		wp_send_json_success( array(
			'message' => __( 'Settings imported successfully.', 'wpo-tweaks' ),
		) );
	}

	/* ============================
	 * Profiles
	 * ============================ */

	/**
	 * AJAX: Apply a predefined profile.
	 */
	public function ajax_apply_profile() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		$profile_id = isset( $_POST['profile'] ) ? sanitize_key( wp_unslash( $_POST['profile'] ) ) : '';
		$profiles   = self::get_profiles();

		// Reset to defaults: use default values directly.
		if ( 'reset' === $profile_id ) {
			$sanitized = Core_Diet_Settings::sanitize( Core_Diet_Settings::get_defaults() );
			update_option( Core_Diet_Settings::OPTION_NAME, $sanitized );

			wp_send_json_success( array(
				'message' => __( 'All settings restored to defaults.', 'wpo-tweaks' ),
			) );
		}

		if ( ! isset( $profiles[ $profile_id ] ) ) {
			wp_send_json_error( __( 'Invalid profile.', 'wpo-tweaks' ) );
		}

		$profile_settings = $profiles[ $profile_id ]['settings'];

		// Merge profile over defaults to ensure all keys exist.
		$new_settings = array_merge( Core_Diet_Settings::get_defaults(), $profile_settings );

		// Sanitize through the same callback.
		$sanitized = Core_Diet_Settings::sanitize( $new_settings );

		update_option( Core_Diet_Settings::OPTION_NAME, $sanitized );

		wp_send_json_success( array(
			'message' => sprintf(
				/* translators: %s: profile name */
				__( 'Profile "%s" applied successfully.', 'wpo-tweaks' ),
				$profiles[ $profile_id ]['label']
			),
		) );
	}

	/**
	 * Get predefined profiles.
	 *
	 * Each profile defines only the settings it wants to change.
	 * All other settings inherit from defaults (false/default).
	 *
	 * @return array
	 */
	public static function get_profiles() {
		return array(
			'blog' => array(
				'label'       => __( 'Personal blog', 'wpo-tweaks' ),
				'icon'        => 'dashicons-admin-post',
				'description' => __( 'Ideal for blogs: removes legacy code and frontend bloat, keeps comments and RSS active.', 'wpo-tweaks' ),
				'settings'    => array(
					// Light: enable all.
					'disable_emojis'         => true,
					'disable_rsd_link'       => true,
					'disable_wlw_manifest'   => true,
					'disable_shortlink'      => true,
					'disable_self_pingbacks' => true,
					'disable_capital_p'      => true,
					'disable_update_notices' => true,
					'disable_email_check'    => true,
					'disable_post_by_email'  => true,
					'disable_comment_pagination' => true,
					'disable_wp_logo_admin_bar'  => false,
					'disable_image_editor'   => false,
					// Moderate: safe ones.
					'disable_oembed'         => false, // Blogs use embeds.
					'disable_rest_api_link'  => true,
					'disable_jquery_migrate' => true,
					'disable_dashicons'      => true,
					'disable_adjacent_posts' => false, // SEO uses these.
					'disable_block_directory'  => true,
					'disable_remote_patterns'  => true,
					'disable_global_styles'    => false,
					'disable_duotone'          => true,
					'disable_avatars'          => false, // Blogs use avatars.
					'disable_comment_threading' => false,
					// Strict: conservative.
					'heartbeat_mode'         => 'reduce',
					'revisions_mode'         => 'limit',
					'revisions_limit'        => 10,
					// Widgets: safe cleanup.
					'disable_welcome_panel'  => true,
					'disable_dashboard_events' => true,
				),
			),

			'woocommerce' => array(
				'label'       => __( 'WooCommerce store', 'wpo-tweaks' ),
				'icon'        => 'dashicons-store',
				'description' => __( 'Optimized for online stores: keeps REST API and comments (for reviews), disables unnecessary frontend bloat.', 'wpo-tweaks' ),
				'settings'    => array(
					// Light: enable all.
					'disable_emojis'         => true,
					'disable_rsd_link'       => true,
					'disable_wlw_manifest'   => true,
					'disable_shortlink'      => true,
					'disable_self_pingbacks' => true,
					'disable_capital_p'      => true,
					'disable_update_notices' => true,
					'disable_email_check'    => true,
					'disable_post_by_email'  => true,
					'disable_comment_pagination' => true,
					'disable_wp_logo_admin_bar'  => false,
					'disable_image_editor'   => false,
					// Moderate: keep REST API and oEmbed.
					'disable_oembed'         => true,
					'disable_rest_api_link'  => false, // WooCommerce needs REST.
					'disable_jquery_migrate' => false, // Some WC extensions need it.
					'disable_dashicons'      => true,
					'disable_adjacent_posts' => true,
					'disable_block_directory'  => true,
					'disable_remote_patterns'  => true,
					'disable_global_styles'    => false,
					'disable_duotone'          => true,
					'disable_avatars'          => false,
					'disable_comment_threading' => false,
					// Strict: keep comments for reviews, REST public.
					'heartbeat_mode'         => 'reduce',
					'disable_comments'       => false,
					'disable_feed_all'       => true,
					'revisions_mode'         => 'limit',
					'revisions_limit'        => 5,
					'disable_sitemap'        => false,
					// Widgets: safe cleanup.
					'disable_welcome_panel'         => true,
					'disable_dashboard_quick_draft' => true,
					'disable_dashboard_events'      => true,
				),
			),

			'landing' => array(
				'label'       => __( 'Landing page', 'wpo-tweaks' ),
				'icon'        => 'dashicons-welcome-view-site',
				'description' => __( 'Maximum cleanup for static landing pages: disables comments, feeds, heartbeat, and most unnecessary features.', 'wpo-tweaks' ),
				'settings'    => array(
					// Light: enable all.
					'disable_emojis'         => true,
					'disable_rsd_link'       => true,
					'disable_wlw_manifest'   => true,
					'disable_shortlink'      => true,
					'disable_self_pingbacks' => true,
					'disable_capital_p'      => true,
					'disable_update_notices' => true,
					'disable_email_check'    => true,
					'disable_post_by_email'  => true,
					'disable_comment_pagination' => true,
					'disable_wp_logo_admin_bar'  => true,
					'disable_image_editor'   => true,
					// Moderate: aggressive.
					'disable_oembed'         => true,
					'disable_rest_api_link'  => true,
					'disable_jquery_migrate' => true,
					'disable_dashicons'      => true,
					'disable_adjacent_posts' => true,
					'disable_block_directory'  => true,
					'disable_remote_patterns'  => true,
					'disable_global_styles'    => false,
					'disable_duotone'          => true,
					'disable_avatars'          => true,
					'disable_comment_threading' => true,
					// Strict: aggressive.
					'heartbeat_mode'         => 'disable',
					'disable_comments'       => true,
					'disable_feed_all'       => true,
					'revisions_mode'         => 'limit',
					'revisions_limit'        => 3,
					'autosave_interval'      => 300,
					'disable_sitemap'        => false,
					'disable_lazy_loading'   => false,
					// Widgets: aggressive cleanup.
					'disable_welcome_panel'         => true,
					'disable_dashboard_quick_draft' => true,
					'disable_dashboard_events'      => true,
					'disable_block_archives'        => true,
					'disable_block_latest_comments' => true,
					'disable_block_calendar'        => true,
					'disable_block_tag_cloud'       => true,
					'disable_block_rss'             => true,
					'disable_widget_archives'       => true,
					'disable_widget_calendar'       => true,
					'disable_widget_meta'           => true,
					'disable_widget_tag_cloud'      => true,
					'disable_widget_rss'            => true,
					'disable_customizer_widgets'    => true,
				),
			),

			'maximum' => array(
				'label'       => __( 'Maximum cleanup', 'wpo-tweaks' ),
				'icon'        => 'dashicons-performance',
				'description' => __( 'Enables everything possible. Review carefully: may break plugins that depend on disabled features.', 'wpo-tweaks' ),
				'settings'    => array(
					// Light: all enabled.
					'disable_emojis'         => true,
					'disable_rsd_link'       => true,
					'disable_wlw_manifest'   => true,
					'disable_shortlink'      => true,
					'disable_self_pingbacks' => true,
					'disable_capital_p'      => true,
					'disable_update_notices' => true,
					'disable_email_check'    => true,
					'disable_post_by_email'  => true,
					'disable_comment_pagination' => true,
					'disable_wp_logo_admin_bar'  => true,
					'disable_image_editor'   => true,
					// Moderate: all enabled.
					'disable_oembed'         => true,
					'disable_rest_api_link'  => true,
					'disable_jquery_migrate' => true,
					'disable_dashicons'      => true,
					'disable_adjacent_posts' => true,
					'disable_block_directory'  => true,
					'disable_remote_patterns'  => true,
					'disable_global_styles'    => true,
					'disable_duotone'          => true,
					'disable_avatars'          => true,
					'disable_comment_threading' => true,
					// Strict: aggressive.
					'heartbeat_mode'         => 'disable',
					'disable_comments'       => true,
					'disable_feed_all'       => true,
					'revisions_mode'         => 'disable',
					'autosave_interval'      => 0,
					'disable_sitemap'        => true,
					'disable_lazy_loading'   => true,
					'disable_fetchpriority'  => true,
					'disable_version_params' => true,
					'disable_feed_comments'    => true,
					'disable_feed_taxonomies'  => true,
					'disable_feed_authors'     => true,
					'disable_feed_search'      => true,
					'disable_feed_links_head'  => true,
					'disable_privacy_tools'    => true,
					// Selective loading: only this profile turns it on (its
					// description already warns to review carefully). Each
					// module is a no-op unless its target plugin is active.
					'selective_woocommerce'    => true,
					'selective_cf7'            => true,
					'selective_blocks'         => true,
					// Widgets: maximum cleanup.
					'disable_welcome_panel'         => true,
					'disable_dashboard_quick_draft' => true,
					'disable_dashboard_events'      => true,
					'disable_block_archives'        => true,
					'disable_block_latest_comments' => true,
					'disable_block_latest_posts'    => true,
					'disable_block_calendar'        => true,
					'disable_block_tag_cloud'       => true,
					'disable_block_rss'             => true,
					'disable_block_search'          => true,
					'disable_widget_archives'       => true,
					'disable_widget_calendar'       => true,
					'disable_widget_meta'           => true,
					'disable_widget_tag_cloud'      => true,
					'disable_widget_rss'            => true,
					'disable_customizer_widgets'    => true,
				),
			),
		);
	}

	/* ============================
	 * Recommendations
	 * ============================ */

	/**
	 * AJAX: Analyze site and return recommendations.
	 */
	public function ajax_analyze() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		$recommendations = $this->get_recommendations();

		wp_send_json_success( array(
			'recommendations' => $recommendations,
			'count'           => count( $recommendations ),
			'estimates'       => self::get_savings_estimates(),
		) );
	}

	/**
	 * Get per-key savings estimates for the JS counter.
	 *
	 * Returns an associative array of key => { requests, kb, queries }.
	 *
	 * @return array
	 */
	public static function get_savings_estimates() {
		return array(
			'disable_emojis'         => array( 2, 16.0, 0 ),
			'disable_rsd_link'       => array( 0, 0.1, 0 ),
			'disable_wlw_manifest'   => array( 0, 0.1, 0 ),
			'disable_shortlink'      => array( 0, 0.1, 0 ),
			'disable_self_pingbacks' => array( 0, 0, 1 ),
			'disable_capital_p'      => array( 0, 0, 0 ),
			'disable_update_notices' => array( 0, 0, 0 ),
			'disable_comment_pagination' => array( 0, 0, 0 ),
			'disable_wp_logo_admin_bar'  => array( 0, 0, 0 ),
			'disable_image_editor'   => array( 0, 0, 0 ),
			'disable_oembed'          => array( 1, 3.0, 1 ),
			'disable_rest_api_link'   => array( 0, 0.1, 0 ),
			'disable_jquery_migrate'  => array( 1, 10.0, 0 ),
			'disable_dashicons'       => array( 1, 36.0, 0 ),
			'disable_adjacent_posts'  => array( 0, 0.2, 2 ),
			'disable_block_directory' => array( 1, 5.0, 0 ),
			'disable_remote_patterns' => array( 1, 0, 1 ),
			'disable_global_styles'   => array( 0, 5.0, 0 ),
			'disable_duotone'         => array( 0, 2.0, 0 ),
			'disable_avatars'         => array( 0, 0, 1 ),
			'disable_comment_threading' => array( 1, 2.0, 0 ),
			'disable_comments'        => array( 0, 0, 5 ),
			'disable_feed_all'        => array( 0, 0.2, 0 ),
			'disable_feed_comments'   => array( 0, 0.1, 0 ),
			'disable_feed_taxonomies' => array( 0, 0.1, 0 ),
			'disable_feed_authors'    => array( 0, 0.1, 0 ),
			'disable_feed_search'     => array( 0, 0.1, 0 ),
			'disable_feed_links_head' => array( 0, 0.2, 0 ),
			'disable_sitemap'         => array( 0, 0, 2 ),
			'disable_lazy_loading'    => array( 0, 0, 0 ),
			'disable_fetchpriority'   => array( 0, 0, 0 ),
			'disable_version_params'  => array( 0, 0, 0 ),
			'disable_privacy_tools'   => array( 0, 0, 1 ),
			'disable_internal_search' => array( 0, 0, 2 ),
			'disable_posts_content_type' => array( 0, 0, 0 ),
			'disable_pages_content_type' => array( 0, 0, 0 ),

			// Performance options (on by default). Conservative estimates:
			// values only where there is a real per-page reduction; the rest
			// reorder or speed up delivery without changing request/query counts.
			'optimize_google_fonts'      => array( 0, 0, 0 ),
			'host_google_fonts'          => array( 0, 0, 0 ),
			'resource_hints'             => array( 0, 0, 0 ),
			'preload_assets'             => array( 0, 0, 0 ),
			'preload_logo'               => array( 0, 0, 0 ),
			'optimize_feeds'             => array( 0, 0, 0 ),
			'disable_pdf_previews'       => array( 0, 0, 0 ),
			'clean_transients'           => array( 0, 0, 2 ),
			'enhance_images'             => array( 2, 0, 0 ),
			'add_image_dimensions'       => array( 0, 0, 0 ),
			'optimize_comment_queries'   => array( 0, 0, 1 ),
			'optimize_main_queries'      => array( 0, 0, 1 ),
			'defer_js'                   => array( 0, 0, 0 ),
			'critical_css_inline'        => array( 0, 0, 0 ),
			'critical_css_defer'         => array( 0, 0, 0 ),
			// Selective loading: savings only apply on the pages without the
			// target content; estimates are a conservative per-page average.
			'selective_woocommerce'      => array( 6, 120.0, 0 ),
			'selective_cf7'              => array( 2, 30.0, 0 ),
			'selective_blocks'           => array( 2, 50.0, 0 ),
			'htaccess_rules'             => array( 0, 0, 0 ),
			'htaccess_expires'           => array( 0, 0, 0 ),
			'htaccess_gzip'              => array( 0, 0, 0 ),
			'htaccess_brotli'            => array( 0, 0, 0 ),
			'htaccess_cache_headers'     => array( 0, 0, 0 ),
			'htaccess_cors_fonts'        => array( 0, 0, 0 ),
			'htaccess_keepalive'         => array( 0, 0, 0 ),
		);
	}

	/**
	 * AJAX: Save multiple recommendation settings at once.
	 *
	 * Receives a JSON object of key => boolean pairs and updates
	 * only those keys in the current settings.
	 */
	public function ajax_save_recommendations() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		$raw = isset( $_POST['settings'] ) ? sanitize_text_field( wp_unslash( $_POST['settings'] ) ) : '';
		$changes = json_decode( $raw, true );

		if ( ! is_array( $changes ) || empty( $changes ) ) {
			wp_send_json_error( __( 'No settings to save.', 'wpo-tweaks' ) );
		}

		$defaults = Core_Diet_Settings::get_defaults();
		$settings = get_option( Core_Diet_Settings::OPTION_NAME, $defaults );

		foreach ( $changes as $key => $value ) {
			$key = sanitize_key( $key );
			if ( ! array_key_exists( $key, $defaults ) ) {
				continue;
			}
			$settings[ $key ] = (bool) $value;
		}

		$sanitized = Core_Diet_Settings::sanitize( $settings );
		update_option( Core_Diet_Settings::OPTION_NAME, $sanitized );

		wp_send_json_success();
	}

	/**
	 * Restore default values for a single tab.
	 *
	 * Resets only the settings that belong to the specified tab,
	 * leaving all other tabs untouched.
	 */
	public function ajax_restore_tab() {
		check_ajax_referer( 'core_diet_tools_nonce', 'security' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( __( 'Unauthorized.', 'wpo-tweaks' ), 403 );
		}

		$tab = isset( $_POST['tab'] ) ? sanitize_key( wp_unslash( $_POST['tab'] ) ) : '';

		$allowed_tabs = array( 'light', 'moderate', 'strict', 'widgets', 'emails' );
		if ( ! in_array( $tab, $allowed_tabs, true ) ) {
			wp_send_json_error( __( 'Invalid tab.', 'wpo-tweaks' ) );
		}

		$tab_keys = Core_Diet_Settings::get_tab_keys( $tab );
		if ( empty( $tab_keys ) ) {
			wp_send_json_error( __( 'No settings found for this tab.', 'wpo-tweaks' ) );
		}

		$defaults = Core_Diet_Settings::get_defaults();
		$current  = get_option( Core_Diet_Settings::OPTION_NAME, $defaults );

		// Only overwrite the keys that belong to this tab.
		foreach ( $tab_keys as $key ) {
			if ( array_key_exists( $key, $defaults ) ) {
				$current[ $key ] = $defaults[ $key ];
			}
		}

		$sanitized = Core_Diet_Settings::sanitize( $current );
		update_option( Core_Diet_Settings::OPTION_NAME, $sanitized );

		wp_send_json_success();
	}

	/**
	 * Analyze the site and return actionable recommendations.
	 *
	 * Only suggests options that are currently disabled (not yet activated).
	 *
	 * @return array
	 */
	public function get_recommendations() {
		$settings        = Core_Diet_Settings::get_instance();
		$recommendations = array();

		// --- Light tab: always safe ---

		$light_always_safe = array(
			'disable_emojis'         => __( 'Modern browsers render emojis natively. Disabling saves 1 HTTP request and ~16 KB.', 'wpo-tweaks' ),
			'disable_rsd_link'       => __( 'RSD link is only needed for XML-RPC clients. Safe to remove.', 'wpo-tweaks' ),
			'disable_wlw_manifest'   => __( 'Windows Live Writer has been discontinued. This serves no purpose.', 'wpo-tweaks' ),
			'disable_shortlink'      => __( 'The ?p=123 shortlink is rarely used and adds nothing.', 'wpo-tweaks' ),
			'disable_self_pingbacks' => __( 'Prevents your site from pinging itself. No downside.', 'wpo-tweaks' ),
			'disable_capital_p'      => __( 'The auto-correction filter is cosmetic and unnecessary.', 'wpo-tweaks' ),
			'disable_comment_pagination' => __( 'Comment pagination creates thin content and duplicate URLs. Safe to disable.', 'wpo-tweaks' ),
			'disable_wp_logo_admin_bar'  => __( 'The WordPress logo in the admin bar serves no functional purpose.', 'wpo-tweaks' ),
			'disable_image_editor'   => __( 'The media library image editor is rarely used. Skips its scripts in the admin.', 'wpo-tweaks' ),
		);

		foreach ( $light_always_safe as $key => $reason ) {
			if ( ! $settings->is_enabled( $key ) ) {
				$recommendations[] = array(
					'key'      => $key,
					'label'    => Core_Diet_Settings::get_field_label( $key ),
					'reason'   => $reason,
					'risk'     => 'safe',
					'tab'      => 'light',
				);
			}
		}

		// --- Moderate tab: conditional ---

		// jQuery Migrate: safe if no legacy plugins.
		if ( ! $settings->is_enabled( 'disable_jquery_migrate' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_jquery_migrate',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_jquery_migrate' ),
				'reason' => __( 'Only needed by plugins using deprecated jQuery methods. Most modern plugins work without it.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'moderate',
			);
		}

		// Block directory and remote patterns.
		if ( ! $settings->is_enabled( 'disable_block_directory' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_block_directory',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_block_directory' ),
				'reason' => __( 'Remote block directory adds external requests in the editor. Safe to disable.', 'wpo-tweaks' ),
				'risk'   => 'safe',
				'tab'    => 'moderate',
			);
		}

		if ( ! $settings->is_enabled( 'disable_remote_patterns' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_remote_patterns',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_remote_patterns' ),
				'reason' => __( 'Prevents WordPress from fetching remote block patterns, reducing editor load time.', 'wpo-tweaks' ),
				'risk'   => 'safe',
				'tab'    => 'moderate',
			);
		}

		// Dashicons on frontend.
		if ( ! $settings->is_enabled( 'disable_dashicons' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_dashicons',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_dashicons' ),
				'reason' => __( 'Dashicons CSS on the frontend is only needed for the admin bar. Safe for logged-out visitors.', 'wpo-tweaks' ),
				'risk'   => 'safe',
				'tab'    => 'moderate',
			);
		}

		// Avatars: suggest disabling if comments are disabled.
		if ( ! $settings->is_enabled( 'disable_avatars' ) ) {
			if ( $settings->is_enabled( 'disable_comments' ) ) {
				$recommendations[] = array(
					'key'    => 'disable_avatars',
					'label'  => Core_Diet_Settings::get_field_label( 'disable_avatars' ),
					'reason' => __( 'Comments are already disabled. Avatars serve no purpose and Gravatar requests waste bandwidth.', 'wpo-tweaks' ),
					'risk'   => 'safe',
					'tab'    => 'moderate',
				);
			}
		}

		// Comment threading.
		if ( ! $settings->is_enabled( 'disable_comment_threading' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_comment_threading',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_comment_threading' ),
				'reason' => __( 'Disabling nested replies removes the comment-reply.js script from the frontend.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'moderate',
			);
		}

		// --- Strict tab: conditional ---

		// Comments: check if site has any recent comments.
		if ( ! $settings->is_enabled( 'disable_comments' ) ) {
			$comment_counts = wp_count_comments();
			$total_comments = isset( $comment_counts->approved ) ? (int) $comment_counts->approved : 0;

			if ( 0 === $total_comments ) {
				$recommendations[] = array(
					'key'    => 'disable_comments',
					'label'  => Core_Diet_Settings::get_field_label( 'disable_comments' ),
					'reason' => __( 'Your site has no approved comments. Disabling comments removes unnecessary code and database queries.', 'wpo-tweaks' ),
					'risk'   => 'recommended',
					'tab'    => 'strict',
				);
			}
		}

		// Sitemap: check if SEO plugin provides one.
		if ( ! $settings->is_enabled( 'disable_sitemap' ) ) {
			$has_seo_sitemap = defined( 'WPSEO_VERSION' )
				|| class_exists( 'RankMath' )
				|| class_exists( 'AIOSEO\\Plugin\\AIOSEO' )
				|| defined( 'JEsuspended_PLUGIN_SLUG' );

			if ( $has_seo_sitemap ) {
				$recommendations[] = array(
					'key'    => 'disable_sitemap',
					'label'  => Core_Diet_Settings::get_field_label( 'disable_sitemap' ),
					'reason' => __( 'An SEO plugin with its own sitemap is active. The native WordPress sitemap is redundant.', 'wpo-tweaks' ),
					'risk'   => 'recommended',
					'tab'    => 'strict',
				);
			}
		}

		// RSS feed links in head: always safe.
		if ( ! $settings->is_enabled( 'disable_feed_links_head' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_feed_links_head',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_feed_links_head' ),
				'reason' => __( 'RSS discovery links in the HTML head are unnecessary if you do not actively use feeds.', 'wpo-tweaks' ),
				'risk'   => 'safe',
				'tab'    => 'strict',
			);
		}

		// Search feeds: safe if no feed readers expected.
		if ( ! $settings->is_enabled( 'disable_feed_search' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_feed_search',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_feed_search' ),
				'reason' => __( 'Search result feeds are rarely subscribed to and expose site queries.', 'wpo-tweaks' ),
				'risk'   => 'safe',
				'tab'    => 'strict',
			);
		}

		// Privacy tools: recommend for non-EU or single-author blogs.
		if ( ! $settings->is_enabled( 'disable_privacy_tools' ) ) {
			$recommendations[] = array(
				'key'    => 'disable_privacy_tools',
				'label'  => Core_Diet_Settings::get_field_label( 'disable_privacy_tools' ),
				'reason' => __( 'Built-in privacy tools can be removed if you handle GDPR compliance through a dedicated plugin.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
			);
		}

		// Selective loading: suggest each module when its target is present.
		if ( ! $settings->is_enabled( 'selective_woocommerce' ) && class_exists( 'WooCommerce' ) ) {
			$recommendations[] = array(
				'key'    => 'selective_woocommerce',
				'label'  => Core_Diet_Settings::get_field_label( 'selective_woocommerce' ),
				'reason' => __( 'WooCommerce loads its styles and scripts on every page. Selective loading removes them where there is no store content. Review the cart behavior if your theme has a custom header mini-cart.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
			);
		}

		if ( ! $settings->is_enabled( 'selective_cf7' ) && class_exists( 'WPCF7' ) ) {
			$recommendations[] = array(
				'key'    => 'selective_cf7',
				'label'  => Core_Diet_Settings::get_field_label( 'selective_cf7' ),
				'reason' => __( 'Contact Form 7 loads its assets on every page. Selective loading keeps them only where a form is detected.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
			);
		}

		if ( ! $settings->is_enabled( 'selective_blocks' )
			&& ( ! function_exists( 'wp_is_block_theme' ) || ! wp_is_block_theme() ) ) {
			$recommendations[] = array(
				'key'    => 'selective_blocks',
				'label'  => Core_Diet_Settings::get_field_label( 'selective_blocks' ),
				'reason' => __( 'Your classic theme loads the block library styles everywhere. Selective loading removes them on pages whose content uses no blocks.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
			);
		}

		// Heartbeat: suggest reducing if still default.
		if ( 'default' === $settings->get( 'heartbeat_mode' ) ) {
			$recommendations[] = array(
				'key'    => 'heartbeat_mode',
				'label'  => Core_Diet_Settings::get_field_label( 'heartbeat_mode' ),
				'reason' => __( 'Reducing the Heartbeat frequency saves AJAX requests without affecting auto-save reliability.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
				'value'  => 'reduce',
			);
		}

		// Revisions: suggest limiting if still default.
		if ( 'default' === $settings->get( 'revisions_mode' ) ) {
			$recommendations[] = array(
				'key'    => 'revisions_mode',
				'label'  => Core_Diet_Settings::get_field_label( 'revisions_mode' ),
				'reason' => __( 'Limiting revisions prevents database bloat. 10 revisions per post is usually more than enough.', 'wpo-tweaks' ),
				'risk'   => 'moderate',
				'tab'    => 'strict',
				'value'  => 'limit',
			);
		}

		return $recommendations;
	}

	/* ============================
	 * Rendering helpers
	 * ============================ */

	/**
	 * Render the Scale tab content (savings, profiles, recommendations).
	 */
	public function render_scale_tab() {
		?>
		<div class="core-diet-tools-sections">
			<?php $this->render_savings_indicator(); ?>
			<?php $this->render_profiles_section(); ?>
			<?php $this->render_recommendations_section(); ?>
		</div>
		<?php
	}

	/**
	 * Render the Tools tab content (import/export only).
	 */
	public function render_tools_tab() {
		?>
		<div class="core-diet-tools-sections">
			<?php $this->render_import_export_section(); ?>
		</div>
		<?php
	}

	/**
	 * Render the savings indicator widget.
	 */
	private function render_savings_indicator() {
		$savings = self::calculate_savings();
		?>
		<div class="core-diet-tools-section core-diet-savings-section">
			<h2><?php esc_html_e( 'Current savings', 'wpo-tweaks' ); ?></h2>
			<p class="core-diet-tab-description">
				<?php esc_html_e( 'Estimated savings based on your current configuration. Values are approximate.', 'wpo-tweaks' ); ?>
			</p>

			<div class="core-diet-savings-grid">
				<div class="core-diet-savings-card">
					<span class="core-diet-savings-value" id="core-diet-savings-requests">
						<?php echo absint( $savings['requests'] ); ?>
					</span>
					<span class="core-diet-savings-label">
						<?php esc_html_e( 'HTTP requests removed', 'wpo-tweaks' ); ?>
					</span>
				</div>
				<div class="core-diet-savings-card">
					<span class="core-diet-savings-value" id="core-diet-savings-kb">
						<?php
						echo esc_html( number_format_i18n( $savings['kb'], 1 ) );
						?>
						<small>KB</small>
					</span>
					<span class="core-diet-savings-label">
						<?php esc_html_e( 'CSS/JS saved', 'wpo-tweaks' ); ?>
					</span>
				</div>
				<div class="core-diet-savings-card">
					<span class="core-diet-savings-value" id="core-diet-savings-queries">
						<?php echo absint( $savings['queries'] ); ?>
					</span>
					<span class="core-diet-savings-label">
						<?php esc_html_e( 'Database queries avoided', 'wpo-tweaks' ); ?>
					</span>
				</div>
				<div class="core-diet-savings-card">
					<span class="core-diet-savings-value" id="core-diet-savings-active">
						<?php echo absint( $savings['active_count'] ); ?>
						<small>/<?php echo absint( $savings['total_count'] ); ?></small>
					</span>
					<span class="core-diet-savings-label">
						<?php esc_html_e( 'Optimizations active', 'wpo-tweaks' ); ?>
					</span>
				</div>
			</div>
		</div>
		<?php
	}

	/**
	 * Render the profiles section.
	 */
	private function render_profiles_section() {
		$profiles = self::get_profiles();
		?>
		<div class="core-diet-tools-section">
			<h2><?php esc_html_e( 'Quick profiles', 'wpo-tweaks' ); ?></h2>
			<p class="core-diet-tab-description">
				<?php esc_html_e( 'Apply a preconfigured set of settings with one click. This will overwrite your current configuration.', 'wpo-tweaks' ); ?>
			</p>

			<div class="core-diet-profiles-grid">
				<?php foreach ( $profiles as $profile_id => $profile ) : ?>
					<div class="core-diet-profile-card">
						<span class="dashicons <?php echo esc_attr( $profile['icon'] ); ?>"></span>
						<h3><?php echo esc_html( $profile['label'] ); ?></h3>
						<p><?php echo esc_html( $profile['description'] ); ?></p>
						<button type="button"
						        class="button core-diet-apply-profile"
						        data-profile="<?php echo esc_attr( $profile_id ); ?>"
						        data-name="<?php echo esc_attr( $profile['label'] ); ?>">
							<?php esc_html_e( 'Apply profile', 'wpo-tweaks' ); ?>
						</button>
					</div>
				<?php endforeach; ?>
			</div>

			<div class="core-diet-reset-wrap">
				<button type="button" class="button core-diet-apply-profile core-diet-reset-btn"
				        data-profile="reset"
				        data-name="<?php esc_attr_e( 'Reset to defaults', 'wpo-tweaks' ); ?>">
					<span class="dashicons dashicons-image-rotate core-diet-btn-icon"></span>
					<?php esc_html_e( 'Reset all settings to defaults', 'wpo-tweaks' ); ?>
				</button>
				<span class="description">
					<?php esc_html_e( 'Disables all toggles and restores select options to their default values.', 'wpo-tweaks' ); ?>
				</span>
			</div>
		</div>
		<?php
	}

	/**
	 * Render the recommendations section.
	 */
	private function render_recommendations_section() {
		?>
		<div class="core-diet-tools-section">
			<h2><?php esc_html_e( 'Recommendations', 'wpo-tweaks' ); ?></h2>
			<p class="core-diet-tab-description">
				<?php esc_html_e( 'Analyze your site and discover which options can be safely applied based on your current setup.', 'wpo-tweaks' ); ?>
			</p>

			<button type="button" class="button button-primary" id="core-diet-analyze-btn">
				<span class="dashicons dashicons-search core-diet-btn-icon"></span>
				<?php esc_html_e( 'Analyze my site', 'wpo-tweaks' ); ?>
			</button>

			<div id="core-diet-recommendations-results" class="core-diet-recommendations-results core-diet-hidden">
				<!-- Populated via AJAX -->
			</div>
		</div>
		<?php
	}

	/**
	 * Render the import/export section.
	 */
	private function render_import_export_section() {
		?>
		<div class="core-diet-tools-section">
			<h2><?php esc_html_e( 'Import / Export', 'wpo-tweaks' ); ?></h2>
			<p class="core-diet-tab-description">
				<?php esc_html_e( 'Export your configuration to a JSON file and import it on another site.', 'wpo-tweaks' ); ?>
			</p>

			<div class="core-diet-import-export-grid">
				<div class="core-diet-ie-card">
					<h3><?php esc_html_e( 'Export settings', 'wpo-tweaks' ); ?></h3>
					<p><?php esc_html_e( 'Download your current DietPress configuration as a JSON file.', 'wpo-tweaks' ); ?></p>
					<button type="button" class="button" id="core-diet-export-btn">
						<span class="dashicons dashicons-download core-diet-btn-icon"></span>
						<?php esc_html_e( 'Export to JSON', 'wpo-tweaks' ); ?>
					</button>
				</div>

				<div class="core-diet-ie-card">
					<h3><?php esc_html_e( 'Import settings', 'wpo-tweaks' ); ?></h3>
					<p><?php esc_html_e( 'Upload a previously exported JSON file to restore settings.', 'wpo-tweaks' ); ?></p>
					<label class="button" id="core-diet-import-label">
						<span class="dashicons dashicons-upload core-diet-btn-icon"></span>
						<?php esc_html_e( 'Select JSON file', 'wpo-tweaks' ); ?>
						<input type="file" id="core-diet-import-file" accept=".json" class="core-diet-hidden">
					</label>
					<span id="core-diet-import-status" class="core-diet-import-status"></span>
				</div>
			</div>
		</div>
		<?php
	}

	/* ============================
	 * Savings calculation
	 * ============================ */

	/**
	 * Calculate estimated savings based on active settings.
	 *
	 * Static estimates per option. Values are approximate and based on
	 * typical WordPress installations.
	 *
	 * @return array With keys: requests, kb, queries, active_count, total_count.
	 */
	public static function calculate_savings() {
		$settings = Core_Diet_Settings::get_instance();

		// Estimated savings per option: array( requests, kb, queries ).
		// Single source of truth, shared with the analyzer (get_savings_estimates).
		$estimates = self::get_savings_estimates();

		$totals = array(
			'requests'     => 0,
			'kb'           => 0.0,
			'queries'      => 0,
			'active_count' => 0,
			'total_count'  => count( $estimates ),
		);

		foreach ( $estimates as $key => $values ) {
			if ( $settings->is_enabled( $key ) ) {
				$totals['requests'] += $values[0];
				$totals['kb']       += $values[1];
				$totals['queries']  += $values[2];
				$totals['active_count']++;
			}
		}

		// Non-boolean savings.
		$heartbeat_mode = $settings->get( 'heartbeat_mode' );
		if ( 'disable' === $heartbeat_mode ) {
			$totals['requests'] += 1;
			$totals['kb']       += 4.0;
			$totals['active_count']++;
		} elseif ( 'reduce' === $heartbeat_mode || 'admin_only' === $heartbeat_mode ) {
			$totals['requests'] += 1;
			$totals['active_count']++;
		}
		$totals['total_count']++;

		$revisions_mode = $settings->get( 'revisions_mode' );
		if ( 'disable' === $revisions_mode ) {
			$totals['queries'] += 3;
			$totals['active_count']++;
		} elseif ( 'limit' === $revisions_mode ) {
			$totals['queries'] += 1;
			$totals['active_count']++;
		}
		$totals['total_count']++;

		$autosave = (int) $settings->get( 'autosave_interval' );
		if ( 60 !== $autosave ) {
			$totals['active_count']++;
			if ( 0 === $autosave ) {
				$totals['requests'] += 1;
				$totals['kb']       += 3.0;
			}
		}
		$totals['total_count']++;

		return $totals;
	}
}